version: "3.9"

services:
  mongodb:
    image: mongo:7
    container_name: insurance-mongodb
    restart: unless-stopped
    ports:
      - "27018:27017"   # 🔥 CHANGED HERE
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: insurance_app
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: insurance-mongo-express
    restart: unless-stopped
    ports:
      - "8082:8081"   # 🔥 CHANGED HERE
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb

volumes:
  mongodb_data: